apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod
  labels:
      role: mongodb
spec:
  serviceName: mongodb
  replicas: 3
  selector:
      matchLabels:
          role: mongodb
  template:
    metadata:
      labels:
        role: mongodb
    spec:
      securityContext:
        runAsUser: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - MainRepSet
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongod-container
          image: localhost:32000/mongodb42rs
          resources:
            requests:
              cpu: 0.2
              memory: 200Mi
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_DEPLOYMENT
              value: replicaset
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                  secretKeyRef:
                      name: admin-pass-mongodb
                      key: pass
            - name: MONGODB_REPLICA_NAME
              value: MainRepSet
            - name: MONGODB_KEYFILE_VALUE
              valueFrom:
                  secretKeyRef:
                      name: keyfile-secret
                      key: internal-auth-mongodb-keyfile
            - name: MONGODB_USER
              valueFrom:
                  secretKeyRef:
                      name: user-mongodb
                      key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                  secretKeyRef:
                      name: user-mongodb
                      key: pass
            - name: MONGODB_DATABASE
              value: testperformance
            - name: MONGODB_SERVICE_NAME
              value: mongodb
            - name: MONGODB_INITIATE_REPLICA
              value: "1"
          volumeMounts:
            - name: mongodb-persistent-storage-claim
              mountPath: /data/db
          securityContext:
            allowPrivilegeEscalation: false
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi


